import { SUPABASE_URL } from "./config.js";

export const state = {
  currentPage: "dashboard",
  isIntegrated: localStorage.getItem("isIntegrated") === "true",
  syncStatus: "idle",
  isLoading: true,
  searchTerm: "",
  sheetUrl: localStorage.getItem("sheetUrl") || SUPABASE_URL,
  isValidating: false,
  barbers: JSON.parse(localStorage.getItem("barbers") || "[]"),
  records: JSON.parse(localStorage.getItem("records") || "[]"),
  clients: JSON.parse(localStorage.getItem("clients") || "[]"),
  procedures: JSON.parse(localStorage.getItem("procedures") || "[]"),
  expenses: JSON.parse(localStorage.getItem("expenses") || "[]"),
  cards: JSON.parse(localStorage.getItem("cards") || "[]"),
  filters: {
    day: new Date().getDate(),
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
  },
  kpis: {
    diario: "R$ 0,00",
    mensal: "R$ 0,00",
    anual: "R$ 0,00",
  },
  charts: {},
  theme: {
    accent: "#D4D4D8",
    accentRgb: "212 212 216",
  },
  profitFilter: "diario",
  editingRecord: null,
  editingClient: null,
  editingProcedure: null,
  clientView: "clients",
  clientSearch: "",
  isClientDropdownOpen: false,
  showEmptySlots: true,
  managementSearch: "",
  isEditModalOpen: false,
  planSearchTerm: "",
  selectedClientId: null,
  paymentHistory: [],
  paymentsFetchedForClientId: null,
  isAddPlanModalOpen: false,
  allPlanPayments: JSON.parse(localStorage.getItem("allPlanPayments") || "[]"),
  editingExpense: null,
  isExpenseModalOpen: false,
  editingCard: null,
  isCardModalOpen: false,
  selectedCardId: null,
  expenseSearchTerm: "",
  expenseStatusFilter: "TODOS",
  expenseSort: "vencimento_asc",
  expensePeriodFilter: "mensal",
  planSort: "nome_asc",
  // UI Settings (Option B)
  barbershopName: localStorage.getItem("barbershopName") || "LUCAS DO CORTE",
  displayMode: localStorage.getItem("displayMode") || "comfortable",
  privacyMode: localStorage.getItem("privacyMode") === "true",
  customLogo: localStorage.getItem("customLogo") || "assets/logo.png",
  isOffline: !navigator.onLine,
};
