import { SUPABASE_URL } from "./config.js";

export const state = {
  currentPage: "dashboard",
  isIntegrated: localStorage.getItem("isIntegrated") === "true",
  syncStatus: "idle",
  searchTerm: "",
  sheetUrl: localStorage.getItem("sheetUrl") || SUPABASE_URL,
  isValidating: false,
  barbers: [],
  records: [],
  clients: [],
  filters: {
    day: new Date().getDate(),
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
  },
  kpis: {
    diario: "R$ 0,00",
    mensal: "R$ 0,00",
    anual: "R$ 0,00",
  },
  charts: {},
  theme: {
    accent: localStorage.getItem("themeAccent") || "#F59E0B",
    accentRgb: localStorage.getItem("themeAccentRgb") || "245 158 11",
  },
  profitFilter: "diario",
  editingRecord: null,
  editingClient: null,
  editingProcedure: null,
  clientView: "clients",
  procedures: [],
  clientSearch: "",
  isClientDropdownOpen: false,
  showEmptySlots: true,
  managementSearch: "",
  isEditModalOpen: false,
  planSearchTerm: "",
  selectedClientId: null,
  paymentHistory: [],
  paymentsFetchedForClientId: null,
  isAddPlanModalOpen: false,
  allPlanPayments: [],
  expenses: [],
  cards: [],
  editingExpense: null,
  isExpenseModalOpen: false,
  editingCard: null,
  isCardModalOpen: false,
  selectedCardId: null,
  expenseSearchTerm: "",
  expenseStatusFilter: "TODOS",
  expenseSort: "vencimento_asc",
  expensePeriodFilter: "mensal",
  planSort: "nome_asc",
};
