-- Migration Data Script
-- Generated based on HTML agenda exports

-- Insert Clientes
INSERT INTO clientes (nome) VALUES ('ADILSON') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('ALBERTO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('ALEX CASA PIO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('ALINHO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('ANDRÉ') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('BARBOSA') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('BERG') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('CARLOS') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('DAVI PIRES') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('DAVI SARINHO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('EDRÍSIO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('Feriado') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('GYAN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('INGLISON') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('ISMAEL JORGE') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('JADSON LUAN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('JOBSON') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('JOHN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('JOÃO CANTOR') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('LUAN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('LUCAS LEAL') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('LUCCA') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('LUIZINHO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('MARLEN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('MATHEUS ALEXANDRE') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('MATHEUS ALMEIDA') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('MAURO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('MAYKO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('NANDO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('NATAN JOEL') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('NETO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('NIKOLAS') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('PEDRO BLACK') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('RHUAN') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('RINALDO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('RODRIGO MELO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('SR. EDVALDO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('VALCÉLIO') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('WAGNER SOUZA') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('WILLINELSON') ON CONFLICT (nome) DO NOTHING;
INSERT INTO clientes (nome) VALUES ('WLLER') ON CONFLICT (nome) DO NOTHING;

-- Insert Procedimentos

-- Insert Agendamentos
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-01', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-02', '15:40', 'MATHEUS ALEXANDRE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-02', '16:20', 'MARLEN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-02', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-02', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-02', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-02', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-02', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-02', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-02', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-03', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-03', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-03', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-03', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-03', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-03', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-03', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-04', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-04', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-04', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-05', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-05', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-06', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-06', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-06', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-06', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-07', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-07', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-07', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-07', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-07', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-08', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-09', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-09', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-09', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-09', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-09', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-10', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-10', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-10', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-10', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-10', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-10', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-10', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-11', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-11', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-11', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-12', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-12', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-13', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-13', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-13', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-13', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-14', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-14', '9:20', 'MATHEUS ALEXANDRE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-14', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-14', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-14', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-14', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-15', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-16', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-16', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-16', '14:20', 'JOÃO CANTOR', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-16', '15:00', 'LUCAS LEAL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-16', '15:40', 'ALEX CASA PIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-16', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-16', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-16', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-17', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-17', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-17', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-17', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-17', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-17', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-17', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-18', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-18', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-18', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-19', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-19', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-20', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-20', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-20', '22:20', 'Feriado', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-20', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-20', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-21', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-21', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-21', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-21', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-21', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-22', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-23', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-23', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-23', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-23', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-23', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-24', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-24', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-24', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-24', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-24', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-24', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-24', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-25', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-25', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-25', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-26', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '10:00', 'PEDRO BLACK', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '10:40', 'SR. EDVALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '13:40', 'BERG', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '14:20', 'WILLINELSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '16:20', 'NETO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '17:00', 'NIKOLAS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '17:40', 'JOBSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '19:00', 'LUIZINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '8:00', 'ANDRÉ', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '8:40', 'MATHEUS ALMEIDA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-26', '9:20', 'EDRÍSIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-02-27', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '10:00', 'ALBERTO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '10:40', 'WAGNER SOUZA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '11:20', 'LUCCA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '13:40', 'RHUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '14:20', 'RINALDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '15:00', 'ADILSON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '7:20', 'CARLOS', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '8:00', 'ALINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '8:40', 'ISMAEL JORGE', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-27', '9:20', 'JOHN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-27', '7:20', 'BARBOSA', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-27', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-28', '7:20', 'VALCÉLIO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-28', '16:20', 'INGLISON', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-28', '18:20', 'LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-28', '8:00', 'DAVI SARINHO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '10:00', 'WLLER', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '13:40', 'NATAN JOEL', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '15:00', 'MAYKO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '17:00', 'JADSON LUAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '17:40', 'NANDO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '19:00', 'GYAN', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '8:00', 'DAVI PIRES', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-04-29', '8:40', 'RODRIGO MELO', 'A DEFINIR', 0.0, 'N/A', '');
INSERT INTO agendamentos (data, horario, cliente, procedimento, valor, forma_pagamento, observacoes) VALUES ('2026-03-30', '8:40', 'MAURO', 'A DEFINIR', 0.0, 'N/A', '');
